# GUT (Godot Unit Test) test file
# Generated by Godot MCP

extends GutTest

# Test basic arithmetic
func test_addition():
	assert_eq(1 + 1, 2, "Addition should work")
	assert_eq(2 + 2, 4, "More addition")

