# Phase 6.B final-pass test suite operation module.
extends RefCounted

var _context
var _legacy
var debug_mode = false
var _exit_code = 0

func setup(context, legacy) -> void:
    _context = context
    _legacy = legacy
    debug_mode = bool(context.debug_mode)

func get_exit_code() -> int:
    return _exit_code

func reset_exit_code() -> void:
    _exit_code = 0

func quit(code := 0) -> void:
    _exit_code = int(code)

func log_debug(message) -> void:
    if _legacy != null and _legacy.has_method("log_debug"):
        _legacy.log_debug(str(message))

func log_info(message) -> void:
    if _legacy != null and _legacy.has_method("log_info"):
        _legacy.log_info(str(message))

func log_error(message) -> void:
    if _legacy != null and _legacy.has_method("log_error"):
        _legacy.log_error(str(message))



func _to_res_path(path: String) -> String:
    return _legacy.to_res_path(path)

func _load_scene_for_edit(scene_path: String) -> Dictionary:
    return _legacy.load_scene_for_edit(scene_path)

func _save_scene_root(scene_root: Node, full_scene_path: String) -> bool:
    return _legacy.save_scene_root(scene_root, full_scene_path)

func _ensure_resource_dir(resource_path: String) -> bool:
    return _legacy.ensure_resource_dir(resource_path)

func _save_resource_to_path(resource: Resource, resource_path: String) -> bool:
    return _legacy.save_resource_to_path(resource, resource_path)

func _parse_color(value, fallback := Color.WHITE) -> Color:
    return _legacy.parse_color(value, fallback)

func _parse_vector2(value, fallback := Vector2.ZERO) -> Vector2:
    return _legacy.parse_vector2(value, fallback)

func _has_property(obj: Object, property_name: String) -> bool:
    return _legacy.has_property(obj, property_name)

func _get_edit_parent(scene_root: Node, parent_path: String) -> Node:
    return _legacy.get_edit_parent(scene_root, parent_path)

func _make_unique_child_name(parent: Node, base_name: String) -> String:
    return _legacy.make_unique_child_name(parent, base_name)


func create_test_suite(params):
    log_info("Creating test suite")

    var test_path = params.test_path
    var target_script = params.get("target_script", null)
    var test_cases = params.get("test_cases", [])
    var include_hooks = params.get("include_hooks", false)

    if debug_mode:
        log_debug("Test path: " + test_path)
        log_debug("Target script: " + str(target_script))
        log_debug("Test cases count: " + str(test_cases.size()))
        log_debug("Include hooks: " + str(include_hooks))

    # Create directory if needed
    var full_test_path = ProjectSettings.globalize_path("res://" + test_path)
    var test_dir = full_test_path.get_base_dir()
    if not DirAccess.dir_exists_absolute(test_dir):
        var dir_result = DirAccess.make_dir_recursive_absolute(test_dir)
        if dir_result != OK:
            log_error("Failed to create test directory: " + test_dir)
            quit(1)
        log_info("Created test directory: " + test_dir)

    # Generate test file content
    var test_content = ""

    # Add header comment
    test_content += "# GUT (Godot Unit Test) test file\n"
    test_content += "# Generated by Godot MCP\n"
    if target_script:
        test_content += "# Testing: " + target_script + "\n"
    test_content += "\n"

    # Extend GutTest
    test_content += "extends GutTest\n\n"

    # Add optional hooks
    if include_hooks:
        test_content += "# Runs before all tests\n"
        test_content += "func before_all():\n"
        test_content += "\tpass\n\n"

        test_content += "# Runs after all tests\n"
        test_content += "func after_all():\n"
        test_content += "\tpass\n\n"

        test_content += "# Runs before each test\n"
        test_content += "func before_each():\n"
        test_content += "\tpass\n\n"

        test_content += "# Runs after each test\n"
        test_content += "func after_each():\n"
        test_content += "\tpass\n\n"

    # Add test cases
    var test_count = 0
    if test_cases.size() > 0:
        for test_case in test_cases:
            var test_name = test_case.get("name", "")
            var description = test_case.get("description", "")
            var setup = test_case.get("setup", "")
            var assertions = test_case.get("assertions", [])

            # Ensure test name starts with "test_"
            if not test_name.begins_with("test_"):
                test_name = "test_" + test_name

            # Add test method
            if description:
                test_content += "# " + description + "\n"
            test_content += "func " + test_name + "():\n"

            # Add setup code if provided
            if setup and setup != "":
                for line in setup.split("\n"):
                    if line.strip_edges() != "":
                        test_content += "\t" + line + "\n"
                test_content += "\t\n"

            # Add assertions
            if assertions.size() > 0:
                for assertion in assertions:
                    test_content += "\t" + assertion + "\n"
            else:
                # Add a pass statement if no assertions
                test_content += "\tpass\n"

            test_content += "\n"
            test_count += 1
    else:
        # Create a default example test if no test cases provided
        test_content += "# Example test - replace with your actual tests\n"
        test_content += "func test_example():\n"
        test_content += "\tassert_eq(1 + 1, 2, \"Math should work\")\n\n"
        test_count = 1

    # Write the test file
    var file = FileAccess.open(full_test_path, FileAccess.WRITE)
    if not file:
        log_error("Failed to create test file: " + full_test_path)
        quit(1)

    file.store_string(test_content)
    file.close()

    log_info("Test file created: " + test_path)

    # Output result
    var output = {
        "test_path": test_path,
        "target_script": target_script if target_script else "",
        "test_count": test_count,
        "include_hooks": include_hooks
    }

    print(JSON.stringify(output))
    log_info("create_test_suite operation completed successfully")

# ===== PHASE 10: TILEMAP & LEVEL DESIGN =====

# Create a TileMap node in a scene
